In [1]:
# Tokenizacion
!pip install -U scikit-learn

   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 640.0 kB/s eta 0:00:17
   ---------------------------------------- 0.1/10.6 MB 812.7 kB/s eta 0:00:14
    --------------------------------------- 0.2/10.6 MB 1.4 MB/s eta 0:00:08
   - -------------------------------------- 0.3/10.6 MB 1.9 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/10.6 MB 2.9 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/10.6 MB 3.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/10.6 MB 4.3 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/10.6 MB 5.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.2/10.6 MB 5.6 MB/s eta 0:00:02
   ---------- ----------------------------- 2.7/10.6 MB 6.2 MB/s eta 0:00:02
   ------------ --------------------------- 3.3/10.6 MB 6.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.8/10.6 MB 7.0 MB/s eta 0:00:01
  

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("df_total.csv",encoding="UTF-8")

In [4]:
df

url  \
0      https://www.larepublica.co/redirect/post/3201905   
1      https://www.larepublica.co/redirect/post/3210288   
2      https://www.larepublica.co/redirect/post/3240676   
3      https://www.larepublica.co/redirect/post/3342889   
4      https://www.larepublica.co/redirect/post/3427208   
...                                                 ...   
1212  https://www.bbva.com/es/como-lograr-que-los-in...   
1213  https://www.bbva.com/es/podcast-como-nos-afect...   
1214   https://www.larepublica.co/redirect/post/3253735   
1215  https://www.bbva.com/es/bbva-y-barcelona-healt...   
1216   https://www.larepublica.co/redirect/post/3263980   

                                                   news           Type  
0     Durante el foro La banca articulador empresari...           Otra  
1     El regulador de valores de China dijo el domin...   Regulaciones  
2     En una industria históricamente masculina como...       Alianzas  
3     Con el dato de marzo el IPC interanual encaden...  Macroeconomia  
4     Ayer en Cartagena se dio inicio a la versión n...           Otra  
...                                                 ...            ...  
1212  En la vida de toda empresa emergente llega un ...     Innovacion  
1213  La espiral alcista de los precios continúa y g...  Macroeconomia  
1214  Las grandes derrotas nacionales son experienci...       Alianzas  
1215  BBVA ha alcanzado un acuerdo de colaboración c...     Innovacion  
1216  Casi entrando a la parte final de noviembre la...       Alianzas  

[1217 rows x 3 columns]

In [11]:
# Separamos los datos en variables de entrada y etiqueta
X = df["news"]
y = df["Type"]

In [6]:
print(df["Type"].value_counts())

Type
Macroeconomia     340
Alianzas          247
Innovacion        195
Regulaciones      142
Sostenibilidad    137
Otra              130
Reputacion         26
Name: count, dtype: int64


In [9]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [13]:
X_train

1147    Con la llegada de Gustavo Petro a la Presidenc...
620     La necesidad de cumplir con el aislamiento obl...
844     La extracción de petróleo y la refinación de a...
388                                                      
475     Desde mañana 31 de agosto al tres de septiembr...
                              ...                        
708     La publicación británica vuelve a reconocer a ...
804     El crecimiento global será en los próximos dos...
744     Seguros Bolívar obtuvo el registro de una pate...
1004    Cada vez son más las fintech que apuestan por ...
756     En medio de la XVI Cumbre de la Alianza del Pa...
Name: news, Length: 973, dtype: object

In [14]:
X_test

819     Esta semana en el 'podcast' de ‘Futuro sosteni...
90      Durante marzo los socios de los emisores de la...
771     Para celebrar el Día Nacional del Tendero la F...
480     El favorito para la presidencia Luiz Inacio Lu...
1050    Apple Inc. aumentando su gasto en podcasts ori...
                              ...                        
745     Durante el primer y segundo trimestre del año ...
406     Para que la electricidad fluya es esencial la ...
622     Desde su lanzamiento en febrero de 2020 y a ci...
598     Imagínense en este país si un candidato tiene ...
667     En el día de la madre sin duda se realizaron d...
Name: news, Length: 244, dtype: object

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
vectorizer = CountVectorizer()

In [28]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_tranformed = vectorizer.transform(X_test)

In [29]:
X_train_tranformed_dense = X_train_transformed.toarray()
print(X_train_tranformed_dense)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 6 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
X_train_transformed

<973x26497 sparse matrix of type '<class 'numpy.int64'>'
	with 232017 stored elements in Compressed Sparse Row format>

In [30]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [32]:
model = MultinomialNB()
model.fit(X_train_transformed,y_train)
y_pred = model.predict(X_test_tranformed)
print(metrics.accuracy_score(y_test,y_pred))

0.7540983606557377


In [33]:
# Stemming

import nltk
from nltk.tokenize import word_tokenize 
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords

In [34]:
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dev\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dev\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [35]:
stemmer = SnowballStemmer("spanish")
def tokenize_and_stem(text):
 tokens = word_tokenize(text.lower())
 stems = [stemmer.stem(token) for token in tokens if token.isalpha()]
 return " ".join(stems)

In [36]:
df["new_stemmer"] = df["news"].apply(tokenize_and_stem)

In [38]:
df["new_stemmer"]

0       durant el for la banc articul empresarial par ...
1       el regul de valor de chin dij el doming que bu...
2       en una industri histor masculin com lo es la a...
3       con el dat de marz el ipc interanual encaden s...
4       ayer en cartagen se dio inici a la version num...
                              ...                        
1212    en la vid de tod empres emergent lleg un momen...
1213    la espiral alcist de los preci continu y gener...
1214    las grand derrot nacional son experient trauma...
1215    bbva ha alcanz un acuerd de colabor con barcel...
1216    casi entrand a la part final de noviembr la ep...
Name: new_stemmer, Length: 1217, dtype: object

In [41]:
X = df["new_stemmer"]
y = df["Type"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
vectorizer = CountVectorizer()
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_tranformed = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_transformed,y_train)

# Medimos el rendimiendo del modelo
y_pred = model.predict(X_test_tranformed)
print(metrics.accuracy_score(y_test,y_pred))

0.7991803278688525


In [46]:
# Lemmatization
import spacy

In [47]:
nlp = spacy.load("es_core_news_sm")

In [49]:
def lemmatize_text(text):
 doc = nlp(text.lower())
 lemmas = [token.lemma_ for token in doc if token.is_alpha]
 return " ".join(lemmas)

In [50]:
df["news_lemma"] = df["news"].apply(lemmatize_text)

In [51]:
df["news_lemma"]

0       durante el foro el banca articulador empresari...
1       el regulador de valor de china decir el doming...
2       en uno industria históricamente masculino como...
3       con el dato de marzo el ipc interanual encaden...
4       ayer en cartagena él dar inicio a el versión n...
                              ...                        
1212    en el vida de todo empresa emergente llegar un...
1213    el espiral alcista de el precio continuar y ge...
1214    el grande derrota nacional ser experiencia tra...
1215    bbva haber alcanzar uno acuerdo de colaboració...
1216    casi entrar a el parte final de noviembre el é...
Name: news_lemma, Length: 1217, dtype: object

In [56]:
X = df["news_lemma"]
y = df["Type"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
vectorizer = CountVectorizer()
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_tranformed = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_transformed,y_train)

# Medimos el rendimiendo del modelo
y_pred = model.predict(X_test_tranformed)
print(metrics.accuracy_score(y_test,y_pred)))

0.8278688524590164


In [57]:
X_train_transformed

<973x16870 sparse matrix of type '<class 'numpy.int64'>'
	with 195350 stored elements in Compressed Sparse Row format>

In [64]:
# Preprocesamiento de la pregunta
def preprocess_question(question):
    # Aplicar el mismo preprocesamiento que se hizo en los datos de entrenamiento
    preprocessed_question = lemmatize_text(question)  # Usar la función de lematización
    preprocessed_question = tokenize_and_stem(preprocessed_question)  # Usar la función de tokenización y stemming
    return preprocessed_question


In [72]:
question = "Full metal"
preprocessed_question = preprocess_question(question.lower())
question_vectorized = vectorizer.transform([preprocessed_question])
predicted_class = model.predict(question_vectorized)

print("El modelo predice que la pregunta pertenece a la clase: ",predicted_class[0])

El modelo predice que la pregunta pertenece a la clase:  Regulaciones
