In [43]:
import pandas as pd

In [44]:
df = pd.read_csv("anime.csv",encoding="UTF-8")
df = df.dropna()

In [45]:
df

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12017 rows x 7 columns]

In [46]:
X = df["name"]
y = df["genre"] 

In [47]:
print(df["genre"].value_counts())

genre
Hentai                                                   816
Comedy                                                   521
Music                                                    297
Kids                                                     197
Comedy, Slice of Life                                    174
                                                        ... 
Adventure, Comedy, Horror, Shounen, Supernatural           1
Comedy, Harem, Romance, School, Seinen, Slice of Life      1
Comedy, Ecchi, Sci-Fi, Shounen                             1
Adventure, Shounen, Sports                                 1
Hentai, Slice of Life                                      1
Name: count, Length: 3229, dtype: int64


In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [49]:
X_train

568                        Seikai no Senki II
10034                                  Pulsar
887                              Ga-Rei: Zero
11557                                  Mejoku
5274                               Burn Up! W
                         ...                 
11605    Choujin Densetsu Urotsukidouji Movie
10007              Poppoya-san: Nonki Ekichou
11568                            Cool Devices
6600                      Gall Force: New Era
11143    Dorei Usagi to Anthony The Animation
Name: name, Length: 9613, dtype: object

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
vectorizer = CountVectorizer()

In [52]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

In [53]:
X_train_transformed_dense = X_train_transformed.toarray()
print(X_train_transformed_dense)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [54]:
X_train_transformed

<9613x10497 sparse matrix of type '<class 'numpy.int64'>'
	with 38049 stored elements in Compressed Sparse Row format>

In [55]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [57]:
model = MultinomialNB()
model.fit(X_train_transformed,y_train)
y_predic = model.predict(X_test_transformed)
print(metrics.accuracy_score(y_test,y_predic))

0.13019966722129783


In [58]:
import spacy
nlp = spacy.load("es_core_news_sm")
def lemmatize_text(text):
 doc = nlp(text.lower())
 lemmas = [token.lemma_ for token in doc if token.is_alpha]
 return " ".join(lemmas)  

In [60]:
df["names_lemma"] = df["name"].apply(lemmatize_text)

In [61]:
df["names_lemma"]

0                                            kimi no na wa
1                          fullmetal alchemist brotherhood
2                                                  gintama
3                                                         
4                                                         
                               ...                        
12289                       toushindai my lover minami tai
12290                                          under world
12291                       violence gekiga david no hoshi
12292    violence gekiga shin david no hoshi inma densetsu
12293                       yasuji no pornoramar yacchimae
Name: names_lemma, Length: 12017, dtype: object